import {StyleProp, TextStyle} from 'react-native';

export const TYPOGRAPHY: {[key: string]: StyleProp<TextStyle>} = {
  HEADER_1: {
    fontFamily: 'Rubik-Regular',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 30,
    lineHeight: 36,
  },
  HEADER_2: {
    fontFamily: 'Rubik-Regular',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 26,
    lineHeight: 31,
  },
  HEADER_3: {
    fontFamily: 'Rubik-Regular',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 20,
    lineHeight: 24,
  },
  HEADER_4: {
    fontFamily: 'Rubik-Regular',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 18,
    lineHeight: 21,
  },
  HEADER_5: {
    fontFamily: 'Rubik-Regular',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 15,
    lineHeight: 18,
  },
  CAPTION: {
    fontFamily: 'Rubik-Medium',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 17,
  },
  BUTTON_LABEL: {
    fontFamily: 'Rubik-Medium',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 17,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  TEXT: {
    fontFamily: 'Rubik-Light',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 14,
    lineHeight: 21,
  },
  TEXT_2: {
    fontFamily: 'Rubik-Medium',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 21,
  },
  TEXT_SECONDARY: {
    fontFamily: 'Rubik-Regular',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 14,
    lineHeight: 21,
  },
  TEXT_LINK: {
    fontFamily: 'Rubik-Regular',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 14,
    lineHeight: 17,
  },
  MENU_ITEM: {
    fontFamily: 'Rubik-Medium',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 14,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
};
